# docker/dev/docker-compose.dev.yml
# Docker Compose para servicios auxiliares en desarrollo
# (Solo RabbitMQ y Redis, ya que usamos Neon para PostgreSQL)

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: xumaa-auth-rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: xumaa
      RABBITMQ_DEFAULT_PASS: password123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_dev_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - xumaa-dev

  redis:
    image: redis:7-alpine
    container_name: xumaa-auth-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - xumaa-dev

  # Opcional: Servicio de email para desarrollo
  mailhog:
    image: mailhog/mailhog
    container_name: xumaa-auth-mailhog-dev
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - xumaa-dev

volumes:
  rabbitmq_dev_data:
  redis_dev_data:

networks:
  xumaa-dev:
    driver: bridge